#BOARD_TAG = nano
#BOARD_SUB = atmega328old
BOARD_TAG = pro
BOARD_SUB = 16MHzatmega328
ARDMK_VENDOR = archlinux-arduino
ARDUINO_PORT = /dev/ttyUSB0
AVRDUDE_CONF = /etc/avrdude.conf
USER_LIB_PATH = ./libs
ARDUINO_SKETCHBOOK = /home/torsten/Arduino/
CXXFLAGS_STD=-std=c++2a

include /usr/share/arduino/Arduino.mk

