BOARD_TAG = nano
BOARD_SUB = atmega328old
ARDMK_VENDOR = archlinux-arduino
ARDUINO_PORT = /dev/ttyUSB0
ARDUINO_LIBS = SPI TFT_22_ILI9225
USER_LIB_PATH = $(HOME)/Arduino/libraries
include /usr/share/arduino/Arduino.mk
CXXFLAGS_STD=-std=c++17
