BOARD_TAG = nano
BOARD_SUB = atmega328
ARDUINO_PORT = /dev/ttyUSB0
ARDUINO_LIBS = SPI TFT_22_ILI9225
ARDUINO_DIR = /opt/arduino-1.8.8
USER_LIB_PATH = $(HOME)/Arduino/libraries
include /usr/local/share/arduino/Arduino.mk
CXXFLAGS_STD=-std=c++11
